# For reference, please look at https://github.com/actions/labeler

GitHub Actions:
- .github/**/*

Price addition:
- 'src/views/AddPriceHome.vue'
- 'src/views/AddPriceSingle.vue'
- 'src/views/AddPriceMultiple.vue'

Brands:
- 'src/views/BrandDetail.vue'

📍 Locations:
- 'src/views/LocationList.vue'
- 'src/views/LocationDetail.vue'

🥫 Product page:
- 'src/views/ProductList.vue'
- 'src/views/ProductDetail.vue'

🔍 Search:
- 'src/views/Search.vue'

Stats:
- 'src/views/Stats.vue'

User:
- 'src/views/UserList.vue'
- 'src/views/UserDetail.vue'

User dashboard:
- 'src/views/UserDashboard*.vue'

⚙️ Settings:
- 'src/views/UserSettings.vue'

Action menus:
- 'src/components/*ActionMenuButton.vue'

Translations:
- 'src/i18n/**/*'
